// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordHasherMock is an autogenerated mock type for the PasswordHasher type
type PasswordHasherMock struct {
	mock.Mock
}

type PasswordHasherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasherMock) EXPECT() *PasswordHasherMock_Expecter {
	return &PasswordHasherMock_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: hash, password
func (_m *PasswordHasherMock) Compare(hash string, password string) error {
	ret := _m.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hash, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PasswordHasherMock_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type PasswordHasherMock_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *PasswordHasherMock_Expecter) Compare(hash interface{}, password interface{}) *PasswordHasherMock_Compare_Call {
	return &PasswordHasherMock_Compare_Call{Call: _e.mock.On("Compare", hash, password)}
}

func (_c *PasswordHasherMock_Compare_Call) Run(run func(hash string, password string)) *PasswordHasherMock_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PasswordHasherMock_Compare_Call) Return(_a0 error) *PasswordHasherMock_Compare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordHasherMock_Compare_Call) RunAndReturn(run func(string, string) error) *PasswordHasherMock_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with given fields: password
func (_m *PasswordHasherMock) Hash(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordHasherMock_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type PasswordHasherMock_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *PasswordHasherMock_Expecter) Hash(password interface{}) *PasswordHasherMock_Hash_Call {
	return &PasswordHasherMock_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *PasswordHasherMock_Hash_Call) Run(run func(password string)) *PasswordHasherMock_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PasswordHasherMock_Hash_Call) Return(_a0 string, _a1 error) *PasswordHasherMock_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordHasherMock_Hash_Call) RunAndReturn(run func(string) (string, error)) *PasswordHasherMock_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordHasherMock creates a new instance of PasswordHasherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHasherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasherMock {
	mock := &PasswordHasherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
