// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	authtoken "github.com/masmuss/gokit-starter/internal/outbound/authtoken"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenIssuerMock is an autogenerated mock type for the RefreshTokenIssuer type
type RefreshTokenIssuerMock struct {
	mock.Mock
}

type RefreshTokenIssuerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenIssuerMock) EXPECT() *RefreshTokenIssuerMock_Expecter {
	return &RefreshTokenIssuerMock_Expecter{mock: &_m.Mock}
}

// IssueRefresh provides a mock function with given fields: ctx, subj
func (_m *RefreshTokenIssuerMock) IssueRefresh(ctx context.Context, subj authtoken.TokenSubject) (string, error) {
	ret := _m.Called(ctx, subj)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefresh")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authtoken.TokenSubject) (string, error)); ok {
		return rf(ctx, subj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authtoken.TokenSubject) string); ok {
		r0 = rf(ctx, subj)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authtoken.TokenSubject) error); ok {
		r1 = rf(ctx, subj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenIssuerMock_IssueRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefresh'
type RefreshTokenIssuerMock_IssueRefresh_Call struct {
	*mock.Call
}

// IssueRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - subj authtoken.TokenSubject
func (_e *RefreshTokenIssuerMock_Expecter) IssueRefresh(ctx interface{}, subj interface{}) *RefreshTokenIssuerMock_IssueRefresh_Call {
	return &RefreshTokenIssuerMock_IssueRefresh_Call{Call: _e.mock.On("IssueRefresh", ctx, subj)}
}

func (_c *RefreshTokenIssuerMock_IssueRefresh_Call) Run(run func(ctx context.Context, subj authtoken.TokenSubject)) *RefreshTokenIssuerMock_IssueRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authtoken.TokenSubject))
	})
	return _c
}

func (_c *RefreshTokenIssuerMock_IssueRefresh_Call) Return(_a0 string, _a1 error) *RefreshTokenIssuerMock_IssueRefresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenIssuerMock_IssueRefresh_Call) RunAndReturn(run func(context.Context, authtoken.TokenSubject) (string, error)) *RefreshTokenIssuerMock_IssueRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshTokenIssuerMock creates a new instance of RefreshTokenIssuerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenIssuerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenIssuerMock {
	mock := &RefreshTokenIssuerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
