// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/masmuss/gokit-starter/internal/modules/auth/domain"

	uuid "github.com/google/uuid"
)

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, input, passwordHash
func (_m *RepositoryMock) CreateAccount(ctx context.Context, input domain.RegisterInput, passwordHash string) (domain.User, error) {
	ret := _m.Called(ctx, input, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegisterInput, string) (domain.User, error)); ok {
		return rf(ctx, input, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegisterInput, string) domain.User); ok {
		r0 = rf(ctx, input, passwordHash)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RegisterInput, string) error); ok {
		r1 = rf(ctx, input, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type RepositoryMock_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.RegisterInput
//   - passwordHash string
func (_e *RepositoryMock_Expecter) CreateAccount(ctx interface{}, input interface{}, passwordHash interface{}) *RepositoryMock_CreateAccount_Call {
	return &RepositoryMock_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, input, passwordHash)}
}

func (_c *RepositoryMock_CreateAccount_Call) Run(run func(ctx context.Context, input domain.RegisterInput, passwordHash string)) *RepositoryMock_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RegisterInput), args[2].(string))
	})
	return _c
}

func (_c *RepositoryMock_CreateAccount_Call) Return(_a0 domain.User, _a1 error) *RepositoryMock_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_CreateAccount_Call) RunAndReturn(run func(context.Context, domain.RegisterInput, string) (domain.User, error)) *RepositoryMock_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *RepositoryMock) FindByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type RepositoryMock_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *RepositoryMock_Expecter) FindByEmail(ctx interface{}, email interface{}) *RepositoryMock_FindByEmail_Call {
	return &RepositoryMock_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *RepositoryMock_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *RepositoryMock_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_FindByEmail_Call) Return(_a0 domain.User, _a1 error) *RepositoryMock_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *RepositoryMock_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *RepositoryMock) FindByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type RepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *RepositoryMock_Expecter) FindByID(ctx interface{}, id interface{}) *RepositoryMock_FindByID_Call {
	return &RepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *RepositoryMock_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *RepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *RepositoryMock_FindByID_Call) Return(_a0 domain.User, _a1 error) *RepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.User, error)) *RepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
