// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// TokenIssuerMock is an autogenerated mock type for the TokenIssuer type
type TokenIssuerMock struct {
	mock.Mock
}

type TokenIssuerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuerMock) EXPECT() *TokenIssuerMock_Expecter {
	return &TokenIssuerMock_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: ctx, userID, orgID, email, role
func (_m *TokenIssuerMock) Issue(ctx context.Context, userID uuid.UUID, orgID uuid.UUID, email string, role string) (string, error) {
	ret := _m.Called(ctx, userID, orgID, email, role)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) (string, error)); ok {
		return rf(ctx, userID, orgID, email, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) string); ok {
		r0 = rf(ctx, userID, orgID, email, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, userID, orgID, email, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenIssuerMock_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuerMock_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orgID uuid.UUID
//   - email string
//   - role string
func (_e *TokenIssuerMock_Expecter) Issue(ctx interface{}, userID interface{}, orgID interface{}, email interface{}, role interface{}) *TokenIssuerMock_Issue_Call {
	return &TokenIssuerMock_Issue_Call{Call: _e.mock.On("Issue", ctx, userID, orgID, email, role)}
}

func (_c *TokenIssuerMock_Issue_Call) Run(run func(ctx context.Context, userID uuid.UUID, orgID uuid.UUID, email string, role string)) *TokenIssuerMock_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *TokenIssuerMock_Issue_Call) Return(_a0 string, _a1 error) *TokenIssuerMock_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenIssuerMock_Issue_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string) (string, error)) *TokenIssuerMock_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenIssuerMock creates a new instance of TokenIssuerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuerMock {
	mock := &TokenIssuerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
