// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// TokenIssuerMock is an autogenerated mock type for the TokenIssuer type
type TokenIssuerMock struct {
	mock.Mock
}

type TokenIssuerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuerMock) EXPECT() *TokenIssuerMock_Expecter {
	return &TokenIssuerMock_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: _a0, _a1, _a2
func (_m *TokenIssuerMock) Issue(_a0 context.Context, _a1 uuid.UUID, _a2 string) (string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenIssuerMock_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuerMock_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 string
func (_e *TokenIssuerMock_Expecter) Issue(_a0 interface{}, _a1 interface{}, _a2 interface{}) *TokenIssuerMock_Issue_Call {
	return &TokenIssuerMock_Issue_Call{Call: _e.mock.On("Issue", _a0, _a1, _a2)}
}

func (_c *TokenIssuerMock_Issue_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 string)) *TokenIssuerMock_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *TokenIssuerMock_Issue_Call) Return(_a0 string, _a1 error) *TokenIssuerMock_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenIssuerMock_Issue_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (string, error)) *TokenIssuerMock_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenIssuerMock creates a new instance of TokenIssuerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuerMock {
	mock := &TokenIssuerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
