// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	authtoken "github.com/masmuss/gokit-starter/internal/outbound/authtoken"
	mock "github.com/stretchr/testify/mock"
)

// TokenVerifierMock is an autogenerated mock type for the TokenVerifier type
type TokenVerifierMock struct {
	mock.Mock
}

type TokenVerifierMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenVerifierMock) EXPECT() *TokenVerifierMock_Expecter {
	return &TokenVerifierMock_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: token
func (_m *TokenVerifierMock) Verify(token string) (authtoken.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 authtoken.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (authtoken.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) authtoken.Claims); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(authtoken.Claims)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenVerifierMock_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenVerifierMock_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *TokenVerifierMock_Expecter) Verify(token interface{}) *TokenVerifierMock_Verify_Call {
	return &TokenVerifierMock_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *TokenVerifierMock_Verify_Call) Run(run func(token string)) *TokenVerifierMock_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenVerifierMock_Verify_Call) Return(_a0 authtoken.Claims, _a1 error) *TokenVerifierMock_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenVerifierMock_Verify_Call) RunAndReturn(run func(string) (authtoken.Claims, error)) *TokenVerifierMock_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenVerifierMock creates a new instance of TokenVerifierMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenVerifierMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenVerifierMock {
	mock := &TokenVerifierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
