// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	authtoken "github.com/masmuss/gokit-starter/internal/infra/authtoken"

	mock "github.com/stretchr/testify/mock"
)

// TokenIssuerMock is an autogenerated mock type for the TokenIssuer type
type TokenIssuerMock struct {
	mock.Mock
}

type TokenIssuerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuerMock) EXPECT() *TokenIssuerMock_Expecter {
	return &TokenIssuerMock_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: ctx, subj
func (_m *TokenIssuerMock) Issue(ctx context.Context, subj authtoken.TokenSubject) (string, error) {
	ret := _m.Called(ctx, subj)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authtoken.TokenSubject) (string, error)); ok {
		return rf(ctx, subj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authtoken.TokenSubject) string); ok {
		r0 = rf(ctx, subj)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authtoken.TokenSubject) error); ok {
		r1 = rf(ctx, subj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenIssuerMock_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuerMock_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - subj authtoken.TokenSubject
func (_e *TokenIssuerMock_Expecter) Issue(ctx interface{}, subj interface{}) *TokenIssuerMock_Issue_Call {
	return &TokenIssuerMock_Issue_Call{Call: _e.mock.On("Issue", ctx, subj)}
}

func (_c *TokenIssuerMock_Issue_Call) Run(run func(ctx context.Context, subj authtoken.TokenSubject)) *TokenIssuerMock_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authtoken.TokenSubject))
	})
	return _c
}

func (_c *TokenIssuerMock_Issue_Call) Return(_a0 string, _a1 error) *TokenIssuerMock_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenIssuerMock_Issue_Call) RunAndReturn(run func(context.Context, authtoken.TokenSubject) (string, error)) *TokenIssuerMock_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenIssuerMock creates a new instance of TokenIssuerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuerMock {
	mock := &TokenIssuerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
